### ISSUE TITLE
Further analysis after object assembly

### ISSUE THREAD

**Issue by pavel-shliaha** [sgibb/topdownr#19]
After the object is assembled it should contain 1-2 spectra per fragmentation condition. The next stage is:

- [x] ~Filter on injection times. The two replicates that have the lowest `log2(deviation)` from the median injection time of the `selMZ` and `AGCTarget` get preserved, others removed: #20~
- [x] ~remove fragment observations that are below a certain threshold of the maximum intensity for that fragment. E.g. in the fragment matrix go row by row and assign NA to values that are lower than the largest value in the row multiplied by specified threshold (I am using 0.1 now): #16~ 
- [x] ~Remove unreplicated fragments that are not seen between replicates of a condition #21~
- [x] ~Now that there is two replicates per condition and filtering on fragment intensity and replication has been performed aggregate the replcas to produce the following statistics per condition: 
  a) number of assigned fragments 
  b) total assigned intensity
  c) proportion of assigned intensity.
  (These stats go to @malenasj and will allow us to understand which parameters contribute most to producing better spectra.) #23~
- [x] ~The matrix is then aggregated differently, so that a new matrix is generated:~
    - ~has bonds as rows (i.e. fragments has been aggregated into, Nterm, Cterm and Both) and columns as conditions. #24~
    - ~aggregated conditions on fragments. Note if filtering has been performed as above, so that all fragments replicate between conditions, then aggregation is just a matter of dropping one replicate~
- [x] ~This allows selection of the best combinations of fragmentation conditions. I will post the code I used for this here (#22).~ The best fragmentation conditions are then added to the matrix generated in 5 for visualisation (#17)
